### ISSUE TITLE
SpringMVC+thymeleaf+Tiles config

### ISSUE THREAD

**Issue by menganox** [thymeleaf/thymeleaf-extras-tiles2#7]
Hello,

I´m facing some beginner problem setting up the configuration of SpringMVC+Tiles+Thymeleaf:

my spring.xml is:

```
<bean id="tilesConfigurer" class="org.thymeleaf.extras.tiles2.spring.web.configurer.ThymeleafTilesConfigurer">
  <property name="definitions">
    <list>
      <value>/WEB-INF/tiles-defs.xml</value>
    </list>
  </property>
</bean>

<bean id="templateResolver"
    class="org.thymeleaf.templateresolver.ServletContextTemplateResolver">
    <property name="prefix" value="/WEB-INF/templates/" />
    <property name="suffix" value=".html" />
    <property name="templateMode" value="XHTML" />
</bean>

<bean id="templateEngine" class="org.thymeleaf.spring3.SpringTemplateEngine">
    <property name="templateResolver" ref="templateResolver" />
    <property name="additionalDialects">
        <set>
            <bean class="org.thymeleaf.extras.tiles2.dialect.TilesDialect"/>
        </set>
    </property>
</bean>

<bean id="tilesViewResolver" class="org.thymeleaf.spring3.view.ThymeleafViewResolver">
    <property name="templateEngine" ref="templateEngine" />
    <property name="viewClass" value="org.thymeleaf.extras.tiles2.spring.web.view.ThymeleafTilesView"/>
    <property name="viewNames" value="*.html, *.xhtml, *.xml" />
    <property name="order" value="1"/>
</bean>
```

and I'm supposing tiles-defs.xml is correctly configured, as web.xml, and so on.
So regarding to that info, is there any mistake I made? Because I don't see any relation between some beans...

Thanks!

**Comment by danielfernandez** [comment]
Your Spring configuration looks alright, at first sight. The _TilesConfigurer_ bean is independent, there is no relation between it and the other beans and that is normal (it mimics the behaviour of Spring's own TilesConfigurer).

Are you receiving any errors? If so, how do they look like?

**Comment by menganox** [comment]
Yes, I'm sorry, I forgot to write the error:

javax.servlet.ServletException: Could not resolve view with name 'welcometiles' in servlet with name 'springDispatcher'

it seems like tile's configuration it is not ok, but I think it is! I'll let you know when the solution is made...

Tiles:

<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tiles-definitions PUBLIC "-//Apache Software Foundation//DTD Tiles Configuration 2.0//EN" "http://tiles.apache.org/dtds/tiles-config_2_0.dtd">

<tiles-definitions>

```
<definition name="baselayout" template="/WEB-INF/templates/baselayout.html">
    <put-attribute name="title" value="Template" type="string" />
    <put-attribute name="header" value="header.html" />
    <put-attribute name="menu" value="menu.html" />
    <put-attribute name="body" value="body.html" />
    <put-attribute name="footer" value="footer.html" />
</definition>

<definition name="welcometiles" extends="baselayout">
    <put-attribute name="title" value="Welcome" type="string" />
    <put-attribute name="body" value="welcome.html" />
</definition>
```

</tiles-definitions>

**Comment by danielfernandez** [comment]
Hi again,

Now I can see your definitions, I can see the errors in your configuration.

Your view resolver (Thymeleaf's) can specify the view names it can resolve by means of the `viewNames` attribute. In your configuration, it reads like this:

```
<property name="viewNames" value="*.html, *.xhtml, *.xml" />
```

Which means that the `ThymeleafViewResolver` will only consider it can handle a view if its name ends with `*.html`, `*.xhtml`, etc.

But your view is called `welcometiles`. It doesn't end with any of those suffixes.

The fact is that the `viewNames` property in _view resolvers_ is only useful when your application has more than one of these (for example, if you are using Thymeleaf for some pages and JSP for some other pages), so that each _view resolver_ can know whether the requested views should be resolved by it or not. So if you don't have more than one view resolver... I would simply remove that property.

But there are some additional problems in your Tiles configuration: you are specifying a template like `/WEB-INF/templates/baselayout.html`, but your Thymeleaf _template resolver_ is already configured to add the `/WEB-INF/templates/` prefix and the `.html` suffix to any template name it is requested, so asking for this template would result in actually looking for `/WEB-INF/templates//WEB-INF/templates/baselayout.html.html`.

You should simply specify your template as `baselayout`. And the same goes for `header`, `menu`, `body`, etc.

Regards,
Daniel.

**Comment by menganox** [comment]
yes! it worked... thanks!
